### ISSUE TITLE
No me pude conectar al broker mqtt de ioticos

### ISSUE THREAD

**Issue by alectro86** [ioticos/esp32_ioticos_broker_hello_world#1]
Probé un programa parecido a éste, que lo usé para conectarme al broker cloudmqtt.com, y me anduvo, pero el mismo programa, le puse las credenciales y todo para conectarme al broker de Ioticos, y no pude.. alguien sabe por qué?. También usé la app Linear MQTT Dashboard y no pude..

**Comment by alectro86** [comment]
Bueno, después de probar y probar. No sé qué paso, pero anduvo

**Comment by Manue-ing** [comment]
Buenas! Me he encontrado con el mismo problema ¿Recuerdas como lo solucionaste?

**Comment by alectro86** [comment]
Hola, la verdad que ya no me acuerdo que es lo que fue, porque despues me puse a probar broker propio en AWS..habra sido algun error de tipeo mio..la verdad que no me acuerdo ya

**Comment by Manue-ing** [comment]
Gracias de todas formas por la respuesta. Creo que el error está relacionado con el topic, ya que utilizo un ejemplo de Arduino donde la nomenclatura de topic de cloudmqtt es "nombre de usuario - topic" y no coincide con la nomenclatura de ioticos. Si recuerdas algo te agradecería que me lo dijeras ya que no se me ocurre que más probar
